
SRC_FORMAT    = mod
MODULA2       = gm2

PROGRAMS      = hello

hello_MAIN    = hello.mod
hello_SOURCE  = 

hello_M2FLAGS = -flibs=iso,pim -g -Iinclude
hello_LDFLAGS = -flibs=iso,pim -g -Iinclude

include Makefile.inc

