
SRC_FORMAT          = mod
MODULA2             = gm2

PROGRAMS            = stringex

stringex_MAIN       = StringEx.mod
stringex_SOURCE     = 

stringex_M2FLAGS    = -flibs=iso,pim -g -Iinclude
stringex_LDFLAGS    = -flibs=iso,pim -g -Iinclude

include Makefile.inc

