
SRC_FORMAT    = mod
MODULA2       = gm2

PROGRAMS      = cat

cat_MAIN      = Cat.mod
cats_SOURCE   = 

cat_M2FLAGS   = -flibs=iso,pim -g -Iinclude
cat_LDFLAGS   = -flibs=iso,pim -g -Iinclude

include Makefile.inc

