
SRC_FORMAT    = mod
MODULA2       = gm2

PROGRAMS      = mylib

mylib_MAIN    = Main.mod
mylib_SOURCE  = MyLib.mod

mylib_M2FLAGS = -flibs=iso,pim -g -Iinclude
mylib_LDFLAGS = -flibs=iso,pim -g -Iinclude

include Makefile.inc

