
SRC_FORMAT    = mod
MODULA2       = gm2

PROGRAMS      = stack

stack_MAIN    = Main.mod
stack_SOURCE  = Stacks.mod

stack_M2FLAGS = -flibs=iso,pim -g -Iinclude
stack_LDFLAGS = -flibs=iso,pim -g -Iinclude

include Makefile.inc

